[global]
template_dir = "views"

[dev]
address = "0.0.0.0"
custom_key = "devEnvironment"

[stage]
address = "0.0.0.0"
custom_key = "stageEnvironment"


# Will need to change it when this will be dockerized.
[global.databases.mysql]
url = "mysql://root:admin@127.0.0.1/practice"