[global]
template_dir = "views"

[dev]
address = "0.0.0.0"
custom_key = "devEnvironment"

[stage]
address = "0.0.0.0"
custom_key = "stageEnvironment"



[global.databases.mysql]
url = "mysql://root:root@127.0.0.1/practice"